name = "localpage-redirect"
account_id = "c45461b00db1d9b25d87a8741db52baf"
main = "src/index.js"
compatibility_date = "2026-08-06"
route = "https://secure.kreokersinc.com/*"

[env.production]
name = "localpage-redirect"
